sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v
  - black buzz/*.py
  - black *.py
  - flake8 buzz/*.py
  - flake8 *.py

after_success:
  - sh .travis/deploy_dockerhub.sh


